### ISSUE TITLE
no popup and console error

### ISSUE THREAD

**Issue by ksdavidc** [joycode-hub/datepicker-plugin#1]
was working but now I am getting error:
```
app.js:1 TypeError: Cannot read properties of null (reading 'createEl')
    at _Datepicker.open (plugin:datepicker:415:47)
    at Object.write (plugin:datepicker:154:25)
    at e.measure (app.js:1:446971)
    at app.js:1:449151
```

[datepicker.log](https://github.com/user-attachments/files/16189637/datepicker.log)

not sure how to debug...

I expect it is a plugin conflict as I have many installed, but wonder if you might have a clue where to look.

**Comment by ksdavidc** [comment]
I thought perhaps it was a conflict with either the Natural Language Dates plugin, or the Templates plugin, but even with these off it doesn't work.

**Comment by joycode-hub** [comment]
Was just testing on a vault with many plugins loaded, got similar errors, on a fresh vault it works normal.
I will be looking into this.

**Comment by joycode-hub** [comment]
The issue was that the element identifier I used to get the parent element for the datepicker element seems to have been too specific, and it changes under some cases, perhaps because of some plugins.

I changed this just to a class name and the problem seems to be fixed.

I created a new release 0.3.5 containing this fix + some other small improvements/fixes

Thank you for opening this issue.

**Comment by joycode-hub** [comment]
Please let me know if you have any other comment before I close this issue.

**Comment by ksdavidc** [comment]
can't check it right away but will soon THANK YOU

**Comment by ksdavidc** [comment]
Success!!! thanks
